K8SPSMDB-998 add automatic storage scaling
percona/k8spsmdb-docs pull request #123
Opened 2024-04-23 23:08 UTC by fiowro

2024-04-26 09:03 UTC, tplavcic requested changes

2024-04-26 09:03 UTC, tplavcic commented on docs/scaling.md
> +Manual scaling is the way to go if you version of the Operator is older than
```suggestion
Manual scaling is the way to go if your version of the Operator is older than
```

2024-04-26 09:05 UTC, tplavcic approved these changes

2024-05-15 11:44 UTC, egegunes requested changes

2024-05-15 11:44 UTC, egegunes commented on docs/scaling.md
> +`replsets.<NAME>.volumeSpec.persistentVolumeClaim.resources.requests.storage` option in the
we also need to mention config server replset

2024-05-15 11:44 UTC, egegunes commented on docs/scaling.md
> +    Automated storage scaling by the Operator is in a technical preview stage
maybe this should live in the beginning of the doc

2024-05-17 09:38 UTC, egegunes approved these changes

2024-05-24 14:53 UTC, merged