K8SPSMDB-287 document vault
percona/k8spsmdb-docs pull request #13
Opened 2022-09-12 12:37 UTC by fiowro

2022-09-13 08:42 UTC, spron-in requested changes

2022-09-13 08:42 UTC, spron-in commented on docs/encryption.md
> +    $ kubectl exec -it pod/vault-service-0 -- vault operator unseal "$unsealKey"
In the latest version of a helm chart it is `vault-0`, not `vault-service-0`.

2022-09-13 08:42 UTC, spron-in commented on docs/encryption.md
> +            vault_ca = /etc/mysql/vault-keyring-secret/ca.cert
Copy paste from MySQL. Wrong path here.

2022-09-13 08:42 UTC, spron-in commented on docs/encryption.md
> +            with your certificate,
where do I get this ca.cert?

2022-09-13 08:50 UTC, spron-in requested changes

2022-09-13 08:50 UTC, spron-in commented on docs/encryption.md
> +             vault_url = vault-service.vault-service.svc.cluster.local
this is also wrong.
1. `vault-service` will be just `vault`
2. `vault-service.vault-service.svc.cluster.local` implies that you are installing vault in `vault-service` namespace which is not done in the examples above.

So it should be smth like `vault.default.svc.cluster.local` if the user follows the instruction.

2022-09-14 10:27 UTC, nmarukovich commented on docs/encryption.md
> +    $ vault login s.VgQvaXl8xGFO1RUxAPbPbsfN
We may add the command output @spron-in what do you think? 
`marukovich@Natalias-MacBook-Pro percona-version-service [psmdb-1.13.0_update_operator_image] $ kubectl exec -it vault-0 -- /bin/sh
/ $ vault login hvs.7hTVYdJjROkpDJAxSLl3HKH9
Success! You are now authenticated. The token information displayed below
is already stored in the token helper. You do NOT need to run "vault login"
again. Future Vault requests will automatically use this token.

Key                  Value
---                  -----
token                hvs.7hTVYdJjROkpDJAxSLl3HKH9
token_accessor       iMGp477aReYkPBWrR42Z3L6R
token_duration       ∞
token_renewable      false
token_policies       ["root"]
identity_policies    []
policies             ["root"]`

2022-09-14 10:28 UTC, nmarukovich commented on docs/encryption.md
> +    ```
`Success! Enabled the kv-v2 secrets engine at: secret/`

2022-09-14 11:01 UTC, nmarukovich commented on docs/encryption.md
> +        ```
`Success! Enabled the file audit device at: file/`

2022-09-15 12:54 UTC, nmarukovich commented
If we want to use tls we need to 
1. generate secret 
kubectl create secret generic vault-secret --from-literal=token="s.VgQvaXl8xGFO1RUxAPbPbsfN" --from-file=ca.crt=<path>/to/ca.crt
2. Add value to config 
tokenFile: /etc/mongodb-vault/token
serverCAFile: /etc/mongodb-vault/ca.crt

and it should work

2022-09-15 16:04 UTC, nmarukovich approved these changes

2022-09-15 17:32 UTC, hors requested changes

2022-09-15 17:32 UTC, hors commented on docs/encryption.md
> +              tokenFile: /etc/mongodb-vault/token
two times `tokenFile`

2022-09-15 17:48 UTC, hors approved these changes

2022-09-15 17:58 UTC, merged